
            // [q_reg_0]"v"(q_nope_reg[0]),
            // [q_reg_1]"v"(q_nope_reg[1]),
            // [q_reg_2]"v"(q_nope_reg[2]),
            // [q_reg_3]"v"(q_nope_reg[3]),
            // [q_reg_4]"v"(q_nope_reg[4]),
            // [q_reg_5]"v"(q_nope_reg[5]),
            // [q_reg_6]"v"(q_nope_reg[6]),
            // [q_reg_7]"v"(q_nope_reg[7]),
            // [q_reg_8]"v"(q_nope_reg[8]),
            // [q_reg_9]"v"(q_nope_reg[9]),
            //
            // [q_reg_10]"v"(q_nope_reg[10]),
            // [q_reg_11]"v"(q_nope_reg[11]),
            // [q_reg_12]"v"(q_nope_reg[12]),
            // [q_reg_13]"v"(q_nope_reg[13]),
            // [q_reg_14]"v"(q_nope_reg[14]),
            // [q_reg_15]"v"(q_nope_reg[15]),
            // [q_reg_16]"v"(q_nope_reg[16]),
            // [q_reg_17]"v"(q_nope_reg[17]),
            // [q_reg_18]"v"(q_nope_reg[18]),
            // [q_reg_19]"v"(q_nope_reg[19]),
            //
            // [q_reg_20]"v"(q_nope_reg[20]),
            // [q_reg_21]"v"(q_nope_reg[21]),
            // [q_reg_22]"v"(q_nope_reg[22]),
            // [q_reg_23]"v"(q_nope_reg[23]),
            // [q_reg_24]"v"(q_nope_reg[24]),
            // [q_reg_25]"v"(q_nope_reg[25]),
            // [q_reg_26]"v"(q_nope_reg[26]),
            // [q_reg_27]"v"(q_nope_reg[27]),
            // [q_reg_28]"v"(q_nope_reg[28]),
            // [q_reg_29]"v"(q_nope_reg[29]),
            //
            // [q_reg_30]"v"(q_nope_reg[30]),
            // [q_reg_31]"v"(q_nope_reg[31]),
            // [q_reg_32]"v"(q_nope_reg[32]),
            // [q_reg_33]"v"(q_nope_reg[33]),
            // [q_reg_34]"v"(q_nope_reg[34]),
            // [q_reg_35]"v"(q_nope_reg[35]),
            // [q_reg_36]"v"(q_nope_reg[36]),
            // [q_reg_37]"v"(q_nope_reg[37]),
            // [q_reg_38]"v"(q_nope_reg[38]),
            // [q_reg_39]"v"(q_nope_reg[39]),
            //
            // [q_reg_40]"v"(q_nope_reg[40]),
            // [q_reg_41]"v"(q_nope_reg[41]),
            // [q_reg_42]"v"(q_nope_reg[42]),
            // [q_reg_43]"v"(q_nope_reg[43]),
            // [q_reg_44]"v"(q_nope_reg[44]),
            // [q_reg_45]"v"(q_nope_reg[45]),
            // [q_reg_46]"v"(q_nope_reg[46]),
            // [q_reg_47]"v"(q_nope_reg[47]),
            // [q_reg_48]"v"(q_nope_reg[48]),
            // [q_reg_49]"v"(q_nope_reg[49]),
            //
            // [q_reg_50]"v"(q_nope_reg[50]),
            // [q_reg_51]"v"(q_nope_reg[51]),
            // [q_reg_52]"v"(q_nope_reg[52]),
            // [q_reg_53]"v"(q_nope_reg[53]),
            // [q_reg_54]"v"(q_nope_reg[54]),
            // [q_reg_55]"v"(q_nope_reg[55]),
            // [q_reg_56]"v"(q_nope_reg[56]),
            // [q_reg_57]"v"(q_nope_reg[57]),
            // [q_reg_58]"v"(q_nope_reg[58]),
            // [q_reg_59]"v"(q_nope_reg[59]),
            //
            // [q_reg_60]"v"(q_nope_reg[60]),
            // [q_reg_61]"v"(q_nope_reg[61]),
            // [q_reg_62]"v"(q_nope_reg[62]),
            // [q_reg_63]"v"(q_nope_reg[63]),
            // [q_reg_64]"v"(q_nope_reg[64]),
            // [q_reg_65]"v"(q_nope_reg[65]),
            // [q_reg_66]"v"(q_nope_reg[66]),
            // [q_reg_67]"v"(q_nope_reg[67]),
            // [q_reg_68]"v"(q_nope_reg[68]),
            // [q_reg_69]"v"(q_nope_reg[69]),
            //
            // [q_reg_70]"v"(q_nope_reg[70]),
            // [q_reg_71]"v"(q_nope_reg[71]),




        //

		// [q_res_0]"s"(q_ptr[0]),
		// [q_res_1]"s"(q_ptr[1]),
		// [q_res_2]"s"(q_ptr[2]),
		// [q_res_3]"s"(q_ptr[3]),
		// [kv_res_0]"s"(kv_ptr[0]),
		// [kv_res_1]"s"(kv_ptr[1]),
		// [kv_res_2]"s"(kv_ptr[2]),
		// [kv_res_3]"s"(kv_ptr[3]),
		// [o_res_0]"s"(o_ptr[0]),
		// [o_res_1]"s"(o_ptr[1]),
		// [o_res_2]"s"(o_ptr[2]),
		// [o_res_3]"s"(o_ptr[3]),
		// [lse_res_0]"s"(lse_ptr[0]),
		// [lse_res_1]"s"(lse_ptr[1]),
		// [lse_res_2]"s"(lse_ptr[2]),
		// [lse_res_3]"s"(lse_ptr[3]),
		// [kv_indptr_res_0]"s"(res_kv_indptr[0]),
		// [kv_indptr_res_1]"s"(res_kv_indptr[1]),
		// [kv_indices_res_0]"s"(kv_indices[0]),
		// [kv_indices_res_1]"s"(kv_indices[1]),
		// [kv_indices_res_2]"s"(kv_indices[2]),
		// [kv_indices_res_3]"s"(kv_indices[3]),
		// [qo_res_0]"s"(res_qo[0]),
		// [qo_res_1]"s"(res_qo[1]),
