name: Aiter Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  # Triggers on PRs targeting `main`

jobs:
  aiter:
    runs-on: mi300x-8gpu
    env:
      DOCKER_IMAGE: "rocm/pytorch:latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
    
      - name: Run the container
        run: |
          echo "Starting container: aiter_test"
          docker run -dt --device=/dev/dri \
          --user=root \
          --network=none \
          --shm-size=16G \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          --name aiter_test \
          ${{ env.DOCKER_IMAGE }}

      - name: Setup-Triton
        run: |
          echo "Setuping Triton..."
          docker exec \
          -w "${{ github.workspace }}" \
          aiter_test \
          ./.github/scripts/build_triton.sh
