name: Aiter Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  # Triggers on PRs targeting `main`

jobs:
  aiter:
    runs-on: mi300x-8gpu
    env:
      DOCKER_IMAGE: "rocm/pytorch:latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
    
      - name: Run the container
        run: |
          echo "Starting container: aiter_test"
          docker run -dt \
          --device=/dev/dri \
          --device=/dev/kfd \
          --group-add $(getent group render | cut -d: -f3) \
          --group-add $(getent group video | cut -d: -f3) \
          --shm-size=16G \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          --name aiter_test \
          ${{ env.DOCKER_IMAGE }}

      - name: Setup-Triton
        run: |
          echo "Setuping Triton..."
          docker exec \
          -w /workspace \
          aiter_test \
          ./.github/scripts/build_triton.sh
      
      - name: Standard Tests
        run: |
          echo "Running Standard Tests..."
          docker exec \
          -w /workspace \
          aiter_test \
          ./.github/scripts/aiter_test.sh

      - name: MultiGPU Tests
        run: |
          echo "Running Standard Tests..."
          docker exec \
          -e MULTIGPU=TRUE \
          -w /workspace \
          aiter_test \
          ./.github/scripts/aiter_test.sh



        
